// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ExampleModalManager",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "ExampleModalManager",
            targets: ["AppModule"],
            bundleIdentifier: "ryunah.ExampleModalManager",
            teamIdentifier: "UY6MP43V7M",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .checkmark),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/mobile-app-frontier/ktSwiftComponent", .branch("fix/modalManager"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ModalManager", package: "ktswiftcomponent")
            ],
            path: "."
        )
    ]
)